namespace DefaultNamespace;

permissionset 50901 "DTC Index Analyzer"
{
    Caption = 'Index Analyzer';
    Assignable = true;

    Permissions =
        table "DTC LRQ FlowField Entry" = X,
        table "DTC VSIFT Entry" = X,
        table "DTC VSIFT Detail" = X,
        table "DTC Index Entry" = X,
        table "DTC Table Index" = X,
        table "DTC Index Selectivity" = X,
        table "DTC Index Detail" = X,
        table "DTC LRQ Entry" = X,
        table "DTC Missing Index" = X,
        table "DTC Page Scripting File Setup" = X,
        tabledata "DTC LRQ FlowField Entry" = RIMD,
        tabledata "DTC VSIFT Entry" = RIMD,
        tabledata "DTC VSIFT Detail" = RIMD,
        tabledata "DTC Index Entry" = RIMD,
        tabledata "DTC Table Index" = RIMD,
        tabledata "DTC Index Selectivity" = RIMD,
        tabledata "DTC Index Detail" = RIMD,
        tabledata "DTC LRQ Entry" = RIMD,
        tabledata "DTC Missing Index" = RIMD,
        tabledata "DTC Page Scripting File Setup" = RIMD,
        codeunit "DTC VSIFT Management" = X,
        codeunit "DTC Index Management" = X,
        codeunit "DTC LRQ Management" = X,
        codeunit "DTC Missing Index Management" = X,
        codeunit "DTC Page Scripting Management" = X,
        codeunit "DTC Index Data Import" = X,
        codeunit "DTC LRQ SQL Parser" = X,
        codeunit "DTC Telemetry Management" = X,
        page "DTC VSIFT Entries" = X,
        page "DTC VSIFT Details" = X,
        page "DTC VSIFT Detail Chart" = X,
        page "DTC VSIFT Group Distr. Chart" = X,
        page "DTC VSIFT Entry Card" = X,
        page "DTC Index Entries" = X,
        page "DTC Table Index List" = X,
        page "DTC Index Selectivity List" = X,
        page "DTC Index Details" = X,
        page "DTC Index Detail Chart" = X,
        page "DTC Index Group Distr. Chart" = X,
        page "DTC LRQ Entries" = X,
        page "DTC LRQ Entry Card" = X,
        page "DTC LRQ Statement FactBox" = X,
        page "DTC LRQ FlowField Entries" = X,
        page "DTC LRQ FF Statement FactBox" = X,
        page "DTC Missing Index List" = X,
        page "DTC Page Scripting File Setup" = X,
        page "DTC API Index Entries" = X,
        page "DTC API Table Indexes" = X,
        page "DTC API VSIFT Entries" = X,
        page "DTC API VSIFT Details" = X,
        page "DTC API Index Selectivity" = X,
        page "DTC API Index Details" = X,
        page "DTC API LRQ Entries" = X,
        page "DTC API LRQ FlowField Entries" = X,
        page "DTC API Missing Indexes" = X;

}
